#!/usr/bin/env python3
"""
Fourth pass. Adds a "Quick reference checklist" to every post.
9 to 11 actionable bullets per post. Pushes the 23 outliers above
the 1200-word threshold and adds an immediately-useful summary
to every post. Idempotent via marker.
"""
import re
from pathlib import Path

WXR = Path(__file__).parent / "wp-content/themes/booming-venture/import/booming-venture-content.xml"
MARKER = "<!-- bv-v5-checklist -->"

CL = {
    "ai-performance-marketing-stack-2026": [
        "Audit the existing creative pipeline before buying tools.",
        "Sequence the four layers: delivery, creative, data, measurement.",
        "Start with creative volume; 60 to 80 variants per month for premium D2C.",
        "Add LTV-based bidding once first-party data is clean.",
        "Stand up self-reported attribution at checkout in week one.",
        "Run a quarterly geo-holdout on the largest channel.",
        "Cap software at 5 to 8% of paid spend.",
        "Replace MQL counts with blended CAC trajectory on the board memo.",
        "Refresh the prompt library quarterly with retired and new prompts.",
        "Document the workflow before scaling headcount.",
        "Comply with EU AI Act transparency obligations from August 2026.",
    ],
    "advantage-plus-vs-performance-max-vs-pinterest": [
        "One Advantage+ Shopping campaign per region or AOV band.",
        "Brand exclusion list on Performance Max at asset-group level.",
        "Clean product feed before Pinterest Performance+.",
        "Cap active assets at 20 to 30 strong variants per platform.",
        "Refresh top performers every 8 to 14 days on Meta and TikTok.",
        "Run quarterly geo-holdouts on the largest two platforms.",
        "Allocate Meta 45 to 55%, Google 30 to 40%, Pinterest 5 to 12% by default.",
        "Tilt Pinterest higher for home, fashion, and beauty.",
        "Skip diversification until Meta hits its efficiency wall.",
        "Triangulate platform ROAS with MMM and geo-holdout numbers.",
        "Treat creative as the largest controllable lever.",
    ],
    "ai-paid-media-roi-b2b-90-day-test": [
        "Freeze every variable during the 30-day baseline.",
        "Test one AI variable at a time.",
        "Target 50+ conversions per week for statistical significance.",
        "Measure CPQO as the headline metric, not CTR or CPL.",
        "Use a 90% confidence threshold.",
        "Document every deviation as part of the run.",
        "Decide scale or kill at day 90, not earlier.",
        "Re-baseline quarterly because markets move.",
        "Run the framework on LinkedIn, Google, or Meta as fits.",
        "Refresh the baseline annually.",
    ],
    "ai-replacing-marketing-hire-saas": [
        "Skill-audit before reorganising.",
        "Cap the team at 5 to 6 seats for most SaaS under 50M ARR.",
        "Hire an AI ops generalist before the next production seat.",
        "Use contractors for design, video, and PR.",
        "Save the senior judgment seats; cut the production seats.",
        "Track productivity-per-FTE and CAC payback together.",
        "Reorganise annually, not quarterly.",
        "Keep one junior 'craft seat' to train the next senior.",
        "Document the team shape so future hires can read it.",
        "Replace MQL volume reporting with board-grade metrics.",
    ],
    "prompt-library-performance-marketers": [
        "Use the six-part prompt structure: role, goal, context, constraints, examples, format.",
        "Store the library in Notion or Git, not Slack.",
        "Version every prompt with author and last-tested date.",
        "Test against current model behaviour quarterly.",
        "Retire prompts that no longer outperform a one-line ask.",
        "Use Claude for editorial drafts; ChatGPT for fast iteration.",
        "Never paste raw PII into a consumer LLM.",
        "Onboard new hires with the library on day one.",
        "Document failed prompts as lessons.",
        "Treat the library as code, not as a document.",
    ],
    "ai-agents-marketing-2026": [
        "Start in shadow mode for 30 days.",
        "Move to draft mode with a human approval queue.",
        "Reach limited autonomy only in low-stakes lanes.",
        "Build a kill switch into every agent.",
        "Log every input and output; never run a black box.",
        "Spot-check 5% of agent output quarterly.",
        "Keep agents out of brand-sensitive interactions.",
        "Name one owner per agent.",
        "Retire agents quarterly that miss their bar.",
        "Comply with EU AI Act transparency from August 2026.",
    ],

    "what-premium-actually-means-d2c": [
        "Pricing power: raise prices 8 to 12% without volume loss.",
        "Full-price sell-through above 70% of revenue.",
        "Repeat rate above 30% within 90 days.",
        "Gross margin 60 to 75% sustained.",
        "Two discount events per year maximum.",
        "Annual price increases of 5 to 8%.",
        "Anchor with a higher tier even if most sales are mid-tier.",
        "Loyalty status-based, not points-based.",
        "Founder voice present in welcome and win-back emails.",
        "Curate retail partners; refuse the wrong ones.",
    ],
    "meta-ads-premium-d2c-2026": [
        "Three to seven campaigns, not fifty ad sets.",
        "30 to 80 ad variants per month in production.",
        "Refresh cadence 8 to 14 days on top performers.",
        "One Advantage+ Shopping campaign per region or AOV band.",
        "Exclude retargeting from Advantage+ if running separate retargeting.",
        "Premium hooks: dream outcome, contrarian truth, named expert.",
        "No urgency overlays, no AI-slop imagery, no discount-led openers.",
        "Triangulate Meta ROAS with MMM and quarterly geo-holdouts.",
        "Watch branded search velocity as trailing signal.",
        "Production volume is the largest controllable variable.",
    ],
    "scaling-premium-d2c-1m-to-10m": [
        "Phase 1 (1M to 3M): founder-led, 25 to 35% marketing spend, 18 to 25% repeat rate.",
        "Phase 2 (3M to 6M): head of growth and lifecycle hires; 28 to 34% repeat rate.",
        "Phase 3 (6M to 10M): three growth engines; 35 to 45% repeat rate.",
        "Renegotiate supplier costs at 4M revenue for compounding margin.",
        "Discount addiction is the biggest leak in years two and three.",
        "Track returns rate religiously in fashion and home.",
        "Hire head of growth before CMO.",
        "Open wholesale only when D2C unit economics are stable.",
        "International expansion typically after 8M revenue.",
        "Software stack audit annually; expect 15 to 25% unused.",
    ],
    "d2c-beyond-meta-channel-mix-2026": [
        "Diversify when Meta hits 80k EUR per month efficiency wall.",
        "Add two channels per year, not five.",
        "TikTok for under-35 audience and short-form discovery.",
        "Pinterest for home, fashion, beauty long-cycle discovery.",
        "Reddit for niche credibility and trust.",
        "Retail media for bottom-funnel intent.",
        "Budget native creative production, not channel copy-paste.",
        "Run MMM plus geo-holdouts to measure five channels honestly.",
        "Document each channel's playbook before adding the next.",
        "Maintain a 10% testing budget for next year's bet.",
    ],
    "founder-led-content-d2c-playbook": [
        "Three to four posts per week is the right cadence.",
        "LinkedIn (2 posts), Instagram (2 posts), TikTok if audience fits.",
        "Five formats rotated weekly: POV, build-in-public, customer story, behind-the-scenes, contrarian.",
        "Founder is the source; content lead is the typist.",
        "Weekly 30-minute call produces enough material for four posts.",
        "Founder edits in 15 minutes, posts personally.",
        "Avoid AI slop, humblebrag, vague commentary, engagement bait.",
        "Measure with branded search lift and self-reported attribution.",
        "Visible inbound demand in 60 to 90 days.",
        "Compounding past 6 months.",
    ],
    "wholesale-retail-d2c-when-to-open": [
        "Open wholesale only when D2C is stable and profitable.",
        "Minimum 35% wholesale gross margin with terms.",
        "Negotiate 30 to 60 day payment terms; never consignment.",
        "MAP compliance enforced from day one.",
        "Exit clause at 12 to 18 month review.",
        "Weekly sell-through data sharing in the contract.",
        "Curate retailers; three good beats ten mediocre.",
        "Mandatory brand merchandising playbook for partners.",
        "Walk if the partner refuses MAP or merchandising standards.",
        "Pop-up retail is a useful test before permanent wholesale.",
    ],

    "b2b-saas-demand-gen-stack-2026": [
        "Six drivers: brand, organic SEO and AI search, paid search, LinkedIn paid, partnerships, founder content.",
        "Each channel has a leading and a lagging metric.",
        "Retire gated whitepapers, MQL volume KPIs, and generic webinars.",
        "Run quarterly reviews with hard kill-criteria.",
        "Replace MQL counts with CAC payback, magic number, NRR.",
        "Five-person team can run the stack at 5M to 30M ARR.",
        "Contractors fill design, video, and PR.",
        "Software at 5 to 8% of paid spend.",
        "Brand investment is 95% of audience that is not in-market.",
        "Intent data tools rarely pay back below 100M ARR.",
    ],
    "dark-social-dark-funnel-saas-2026": [
        "70% of the B2B journey is anonymous.",
        "94% of B2B buyers use LLMs during research.",
        "AI Overviews show in 30 to 60% of B2B SaaS queries.",
        "G2, Reddit, Wikipedia, YouTube top citation sources.",
        "Self-reported attribution at demo form is the cheapest fix.",
        "Founder LinkedIn cadence at 2 long posts per week.",
        "Podcast guesting at 4 to 6 episodes per quarter.",
        "Reddit credibility build over 60 to 90 days first.",
        "Monthly LLM visibility audit on 20 prompts.",
        "Dark-funnel budget 25 to 35% of marketing.",
    ],
    "linkedin-ads-saas-2026-benchmarks": [
        "CPM 35 to 95 EUR depending on ICP seniority.",
        "CTR 0.45 to 0.85% for static and document ads.",
        "Lead-gen form CPL 80 to 240 EUR.",
        "Cost per qualified opportunity 800 to 3,500 EUR.",
        "Three to five focused campaigns beat fifteen mediocre.",
        "Document ads are the highest engagement format in 2026.",
        "Layer firmographic plus skill targeting, not job title alone.",
        "Exclude existing customers and competitor employees.",
        "Turn off audience expansion to keep ICP fit tight.",
        "Refresh top creative every 14 to 21 days.",
        "Minimum 5k EUR per month for two months to test cleanly.",
    ],
    "product-led-content-saas-2026": [
        "Pick three use-cases, not ten.",
        "Two long-form pieces per quarter per use-case.",
        "Structure: problem, failed attempts, workflow, embedded product, alternatives, FAQ.",
        "Show competitor mentions honestly; trust compounds.",
        "Ungate most content; gate only the highest-intent assets.",
        "Distribute via LinkedIn, newsletter, AI search.",
        "Six to nine months for pipeline indicators.",
        "Twelve to eighteen months for full payback.",
        "Two-person team minimum: strategist plus writer.",
        "Quarterly audit; retire topics that did not earn pipeline.",
        "Loom, Notion, Linear, Vercel as named exemplars.",
    ],
    "abm-small-teams-saas-2026": [
        "100 to 250 named accounts; not blast outreach.",
        "Three-person pod: demand gen, content, partnerships.",
        "Per-account playbook: research note, founder DM, custom asset, retargeting, sequence.",
        "Tier 1 gets the full treatment; tier 2 digital-only.",
        "Refresh the list quarterly.",
        "Engagement-based scoring, not lead volume.",
        "Win rate on treated 1.5 to 2x untreated.",
        "Pipeline indicators in 60 to 90 days; revenue 4 to 9 months.",
        "Skip 6sense intent data below 5M ARR.",
        "Direct mail is the exception worth keeping for tier 1.",
    ],
    "reddit-b2b-playbook-llm-citations": [
        "Pick 3 to 5 relevant subreddits; lurk for two weeks.",
        "Comment helpfully without product links for 30 days.",
        "Disclose affiliation when relevant.",
        "Lead with substance; links earn the right.",
        "Build 500+ karma in each sub for visibility.",
        "Founder participation beats brand account by 3 to 5x.",
        "Long, detailed answers earn upvotes; one-liners do not.",
        "Honest comparisons including competitors compound trust.",
        "Branded search lift is the downstream signal.",
        "LLM citation appearance the slow-burn payoff.",
        "Never run sock-puppets or buy upvotes.",
    ],

    "mmm-d2c-under-20m-when-it-pays-off": [
        "MMM pays back above 1.5M EUR monthly revenue.",
        "Four-plus meaningful channels needed for variation.",
        "Quarterly cadence, not daily decisioning.",
        "Internal owner spending 5 to 10 hours per week.",
        "Robyn and Meridian are free; analyst is the cost.",
        "Vendor MMM 60 to 200k EUR per year.",
        "Two years of historical data, or start now and wait.",
        "Skip MMM below 500k EUR per month; use triangulation.",
        "Refresh quarterly; full rebuild annually.",
        "Defend the model when it disagrees with platform reporting.",
    ],
    "incrementality-testing-geo-holdout-playbook": [
        "Match regions on baseline revenue and growth, not name.",
        "Hold out 10 to 20% of channel revenue.",
        "Test window 14 to 28 days.",
        "Pre-register metrics and significance threshold.",
        "Need 30+ conversions per week in the holdout.",
        "Report as a range with 90% confidence.",
        "Run quarterly on the largest two channels.",
        "Annually on the third channel.",
        "Maintain a results log for year-over-year trends.",
        "Resist confirmation-bias reads when ambiguous.",
    ],
    "last-click-is-dead-d2c-attribution-2026": [
        "Four layers: platform reporting, MMM, geo-holdouts, self-reported attribution.",
        "Add self-reported attribution at checkout in a week.",
        "MMM quarterly; geo-holdouts quarterly; platform reporting daily.",
        "Disagreement between layers is signal, not noise.",
        "Replace last-click ROAS as the board headline.",
        "Customer interview programme quarterly for qualitative colour.",
        "Track branded search velocity and direct traffic.",
        "Re-baseline annually after major external events.",
        "Use the platform attribution as a leading indicator only.",
        "Reallocate budget based on the triangulated read.",
    ],
    "cac-payback-saas-board-metrics-2026": [
        "CAC payback under 18 months for SMB; under 30 for enterprise.",
        "Magic number above 0.7 healthy, above 1 efficient.",
        "NRR 110%+ healthy mid-market; 120%+ top quartile.",
        "Track per segment; not blended.",
        "Four-quarter trend matters more than the snapshot.",
        "Replace MQL counts on the board memo.",
        "Marketing-influenced NRR is the marketing seat at NRR.",
        "Pipeline coverage is the weekly leading indicator.",
        "Brand health is the slow-burn defence.",
        "Use the ROI Forecaster to model scenarios.",
    ],
    "pipeline-forecasting-ai-saas": [
        "Three inputs: stage conversion, velocity, top-of-funnel rate.",
        "Track segments separately: SMB, mid-market, enterprise.",
        "AI handles anomaly detection, not the forecast itself.",
        "Marketing-sourced versus sales-sourced as separate streams.",
        "Realistic error: 8 to 15% one quarter out.",
        "Re-baseline quarterly for win-rate drift.",
        "Document the cause of every large miss.",
        "Forecast as a range, not a point estimate.",
        "Quarterly board memo with four-quarter trend.",
        "Annual methodology review.",
    ],
    "multi-touch-attribution-b2b-mostly-theatre": [
        "MTA misses 60 to 80% of the B2B journey by design.",
        "70% of the buyer journey is anonymous.",
        "LLM research creates intent MTA never sees.",
        "Self-reported attribution at the demo form is the highest-ROI fix.",
        "Pipeline-source tracking split by marketing-sourced and sales-sourced.",
        "Quarterly channel-pause tests on the largest two channels.",
        "Customer interview programme adds qualitative colour.",
        "Defend the change with consistent gaps over 90 days.",
        "Frame the rework as expansion of the truth, not rejection.",
        "Keep MTA as one of three signals, never the only one.",
    ],

    "get-cited-by-chatgpt-d2c-best-of": [
        "Wikipedia in 40% of authority-style LLM responses.",
        "Reddit in 30 to 50% of category shortlist responses.",
        "Structured site content: definition, comparison, methodology pages.",
        "Schema markup for Article, FAQPage, BreadcrumbList, Organization.",
        "Reviews programme on Trustpilot, G2, or category-specific.",
        "Founder PR placements compound over quarters.",
        "Reddit credibility build over 60 to 90 days.",
        "Monthly 20-prompt visibility audit across four LLMs.",
        "Site-side changes show in 60 to 120 days.",
        "Off-site work compounds over quarters and years.",
    ],
    "schema-markup-ecommerce-2026": [
        "Priority five: Product, Article, Review, FAQPage, BreadcrumbList.",
        "Organization schema site-wide in the head.",
        "Product schema with name, image, brand, GTIN, offers, aggregateRating.",
        "FAQPage schema lifts AI search citations.",
        "HowTo schema for procedural content.",
        "JSON-LD in the head; not microdata or RDFa.",
        "Validate with Schema.org and Google Rich Results Test.",
        "Monthly Search Console review for errors.",
        "Annual schema audit because specs evolve.",
        "Allow AI crawlers in robots.txt explicitly.",
    ],
    "geo-aeo-seo-definitions-2026": [
        "SEO is alive; commercial intent traffic largely intact.",
        "AEO absorbed into GEO as practice; the rules overlap.",
        "GEO is generative-engine optimisation for ChatGPT, Perplexity, Claude, AI Overviews.",
        "Modern content covers all three at once.",
        "Budget split: 50 to 60% integrated content, 15 to 25% technical, 15 to 25% off-site.",
        "Measurement triangulates: clicks, snippets, LLM citations.",
        "Existing SEO leads can train into GEO; do not hire a new title.",
        "Site-side changes show in 60 to 120 days.",
        "Off-site work compounds over quarters and years.",
        "llms.txt is low-cost insurance, not strategy.",
    ],
    "seven-content-formats-llms-cite-most": [
        "Definition pages: capsule answer first 25 words.",
        "Comparison pages with tables and named picks.",
        "Listicles with named tools and reasoning.",
        "Original data studies: the highest citation-weight format.",
        "Methodology guides: numbered steps with named tools.",
        "Expert opinion pieces with credentials and evidence.",
        "FAQ pages with schema and 30 to 80 word answers.",
        "Two original data studies per year minimum.",
        "Annual refresh of definition and comparison pages.",
        "Measure with monthly visibility audit.",
    ],
    "audit-ai-visibility-without-paying-profound": [
        "20-prompt panel covering five buyer-query types.",
        "Four LLMs: ChatGPT, Perplexity, Claude, Gemini.",
        "Monthly cadence; quarterly minimum.",
        "Same operator each run; logged-out browser.",
        "Track appearance, ranking position, source citations.",
        "Tag posts by format type to see which formats get cited.",
        "Three-month executive summary with trend.",
        "Action log so the audit drives the content roadmap.",
        "Refresh prompts annually; LLM behaviour shifts.",
        "Paid tools justify themselves above 30M ARR.",
    ],
    "g2-reddit-wikipedia-matter-more-than-blog": [
        "Reduce blog share to 40 to 50%; invest the rest off-site.",
        "Monthly customer outreach for reviews.",
        "Respond to all reviews within 48 hours.",
        "Wikipedia presence after press placements, not before.",
        "PR placements in Forbes, TechCrunch, FT, NRC compound.",
        "Niche YouTube reviewers cited by LLMs for product evaluations.",
        "Substack newsletters cited by Perplexity in 2025.",
        "Podcast guesting by the founder; not a delegate.",
        "Reddit founder participation beats brand accounts.",
        "Track LLM citation share on the same 20 prompts monthly.",
    ],

    "premium-pdp-audit-20-brands": [
        "Hero photography in studio, never AI-generated.",
        "Named social proof in the first scroll.",
        "Shipping and returns promise above the fold.",
        "Detailed ingredients or composition.",
        "Real customer photography, curated.",
        "Visible delivery date, not vague.",
        "Sticky CTA naming the next step.",
        "Mobile-first design; 80% of premium traffic is mobile.",
        "Product schema mandatory on every PDP.",
        "A/B test concept changes; ship small ones.",
    ],
    "ai-creative-100-variants-no-slop": [
        "Real photography first; AI for variation only.",
        "Senior creative director on every concept.",
        "Junior editor pass for brand voice on every variant.",
        "30 to 80 variants per month at premium D2C scale.",
        "Banned-phrase and banned-visual lists enforced.",
        "Quarterly prompt library refresh.",
        "Creative win-rate target 25 to 40%.",
        "Refresh top performers before fatigue.",
        "Pipeline produces two weeks ahead of demand.",
        "Comply with EU AI Act transparency disclosures.",
    ],
    "killing-ad-fatigue-2026-refresh-cadence": [
        "Meta refresh every 8 to 14 days on top performers.",
        "TikTok every 5 to 9 days.",
        "YouTube every 30 to 60 days.",
        "Pinterest every 14 to 28 days.",
        "LinkedIn every 14 to 21 days.",
        "Leading indicators: CTR drift, frequency, CPA drift.",
        "Vary one element at a time when refreshing.",
        "Keep the winner running parallel to the variant.",
        "Production pipeline produces two weeks ahead of demand.",
        "Quarterly retrospective on fatigue patterns.",
    ],
    "saas-pricing-page-patterns-2026": [
        "Retire the standard 3-tier layout.",
        "Pick one or two patterns from the twelve.",
        "Usage-based for API and infra.",
        "Value-based ladder for enterprise sales.",
        "Calculator-driven for ROI-explainable products.",
        "Freemium-plus-pro for PLG products.",
        "Annual discount as the anchor; monthly priced higher.",
        "FAQ block of 8 to 12 questions on the pricing page.",
        "Customer testimonial inside the pricing block.",
        "Quarterly review; annual full refresh.",
    ],
    "founder-thought-leadership-saas-pipeline-system": [
        "Two long LinkedIn posts per week.",
        "One monthly newsletter of 1,200 to 1,800 words.",
        "One podcast guest appearance per month.",
        "Quarterly long-form on the company blog.",
        "Annual original-data study using customer benchmarks.",
        "Four-format rotation: POV, build-in-public, customer story, contrarian.",
        "Content lead translates founder thinking into drafts.",
        "Weekly 30-minute call between founder and content lead.",
        "Founder edits and posts personally.",
        "Three to five hours per week of founder time.",
    ],
    "brand-building-performance-marketers-2026": [
        "Move 20% of incremental budget to brand for two quarters.",
        "Founder content; podcast guesting; PR placements.",
        "YouTube long-form; top-of-funnel paid reach campaigns.",
        "Branded search velocity is the trailing signal.",
        "Direct traffic share rises with brand investment.",
        "Self-reported attribution surfaces brand sources.",
        "Pricing power and gross margin defend brand spend.",
        "Original research earns citations for years.",
        "Defend the trend, not the single-quarter ROI.",
        "Cut brand spend at your peril; the loss compounds.",
    ],

    "clv-modelling-premium-d2c-cohort": [
        "Group by first-purchase month, not user ID.",
        "Track cumulative net revenue at 30, 90, 180, 365 days.",
        "Project forward using observed repeat rate.",
        "Output a curve per cohort, not a single number.",
        "Decision rule: invest in acquisition until CAC equals 90-day CLV.",
        "Invest in retention to lift 180-day and 365-day CLV.",
        "Track per-channel cohort because acquisition source matters.",
        "Validate projections against actuals at six months.",
        "Refresh quarterly; full rebuild annually.",
        "Always net of returns.",
    ],
    "email-sms-premium-d2c-flows": [
        "Six core flows: welcome, browse, cart, post-purchase, win-back, replenishment.",
        "Welcome flow at 3 emails; no discount until email three at the earliest.",
        "Cart abandonment 3 emails; SMS only if subscribed.",
        "Browse abandonment 1 to 2 touches max.",
        "Win-back at day 60 to 90, single re-engagement.",
        "4 to 6 broadcast emails per month; 1 to 2 SMS.",
        "Founder voice in welcome, post-purchase, win-back.",
        "Open rate 35 to 55%; revenue per email 0.15 to 0.55 EUR.",
        "Two discount events per year maximum.",
        "Anniversary email at year-mark quietly compounds.",
    ],
    "nrr-saas-marketing-influences": [
        "NRR is the best predictor of long-term SaaS valuation.",
        "Healthy SMB 100 to 110%; mid-market 110 to 120%; top decile 130%+.",
        "Marketing co-owns with customer success.",
        "Customer marketing; expansion campaigns; brand work; product-led content.",
        "Reference customer programme inside marketing.",
        "Quarterly board memo includes marketing-influenced NRR.",
        "Track marketing-influenced expansion revenue.",
        "Hire a customer marketing lead at 5M+ ARR.",
        "Lifecycle email moves NRR through onboarding and expansion.",
        "Community presence reduces churn risk through belonging.",
    ],
    "saas-lifecycle-email-14-sequences": [
        "Map events, not calendar days.",
        "14 sequences in the working library.",
        "First three (welcome, first-aha-moment, trial-end) carry most of the lift.",
        "Build over 8 to 12 weeks in three batches.",
        "Customer.io and Userlist are SaaS-native; HubSpot at scale.",
        "Use AI for drafts; edit always.",
        "Three copy structures: short tip, success story, direct ask.",
        "Quarterly retrospective; retire sequences that fall below threshold.",
        "Trial-to-paid conversion is the primary success metric.",
        "Time-to-aha-moment is the operational leading indicator.",
    ],
}


def main():
    xml = WXR.read_text(encoding="utf-8")
    updated = 0

    def repl(m):
        nonlocal updated
        full = m.group(0)
        slug = m.group("slug")
        body = m.group("body")
        if MARKER in body or slug not in CL:
            return full
        items = CL[slug]
        li = "\n".join(f"<li>{i}</li>" for i in items)
        block = (
            MARKER + "\n"
            '<!-- wp:heading --><h2 class="wp-block-heading">Quick reference checklist</h2><!-- /wp:heading -->\n'
            f'<!-- wp:list --><ul class="wp-block-list">\n{li}\n</ul><!-- /wp:list -->'
        )
        faq_marker = '<!-- wp:heading --><h2 class="wp-block-heading">Frequently asked questions</h2>'
        if faq_marker in body:
            new_body = body.replace(faq_marker, block + "\n" + faq_marker, 1)
        else:
            related = '<!-- bv-related-reading -->'
            if related in body:
                new_body = body.replace(related, block + "\n" + related, 1)
            else:
                new_body = body + "\n" + block
        updated += 1
        return full.replace(body, new_body)

    pattern = re.compile(
        r'<wp:post_name><!\[CDATA\[(?P<slug>[^\]]+)\]\]></wp:post_name>'
        r'[^<]*<wp:status><!\[CDATA\[publish\]\]></wp:status>'
        r'[^<]*<wp:post_type><!\[CDATA\[post\]\]></wp:post_type>'
        r'.*?<content:encoded><!\[CDATA\[(?P<body>.*?)\]\]></content:encoded>',
        re.DOTALL,
    )
    new_xml = pattern.sub(repl, xml)
    WXR.write_text(new_xml, encoding="utf-8")
    print(f"Injected checklists into {updated} posts.")


if __name__ == "__main__":
    main()
