<?php
/**
 * Title: UNIFY Framework ,  5 pillars
 * Slug: booming-venture/unify-framework
 * Categories: booming-venture/sections
 * Viewport Width: 1400
 */
?>
<!-- wp:group {"tagName":"section","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"backgroundColor":"base-50","layout":{"type":"constrained"}} -->
<section class="wp-block-group has-base-50-background-color has-background" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)">
	<!-- wp:group {"layout":{"type":"constrained","contentSize":"880px"}} -->
	<div class="wp-block-group">
		<!-- wp:paragraph {"align":"center","style":{"typography":{"textTransform":"uppercase","letterSpacing":"0.12em","fontWeight":"600"}},"fontSize":"sm","textColor":"venture-700"} -->
		<p class="has-text-align-center has-venture-700-color has-text-color has-sm-font-size" style="font-weight:600;text-transform:uppercase;letter-spacing:0.12em">Our Methodology</p>
		<!-- /wp:paragraph -->
		<!-- wp:heading {"textAlign":"center","level":2,"fontSize":"6xl"} --><h2 class="wp-block-heading has-text-align-center has-6-xl-font-size">The <span class="bv-gradient-text">UNIFY</span> Framework™</h2><!-- /wp:heading -->
		<!-- wp:paragraph {"align":"center","fontSize":"xl","textColor":"muted"} -->
		<p class="has-text-align-center has-muted-color has-text-color has-xl-font-size">Five pillars. One growth engine. The proven system we use to unify brand, performance, and product into compounding revenue.</p>
		<!-- /wp:paragraph -->
	</div>
	<!-- /wp:group -->

	<!-- wp:columns {"align":"wide"} -->
	<div class="wp-block-columns alignwide">
		<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"border":{"radius":"1rem"},"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40"}},"shadow":"var:preset|shadow|sm"},"backgroundColor":"base"} --><div class="wp-block-group has-base-background-color has-background" style="border-radius:1rem;padding:var(--wp--preset--spacing--40);box-shadow:var(--wp--preset--shadow--sm)"><!-- wp:heading {"level":3,"fontSize":"2xl","textColor":"booming-700"} --><h3 class="wp-block-heading has-booming-700-color has-text-color has-2-xl-font-size">U</h3><!-- /wp:heading --><!-- wp:heading {"level":4,"fontSize":"lg"} --><h4 class="wp-block-heading has-lg-font-size">Understand</h4><!-- /wp:heading --><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color">Deep-dive on customers, market, and the real drivers of growth.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
		<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"border":{"radius":"1rem"},"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40"}},"shadow":"var:preset|shadow|sm"},"backgroundColor":"base"} --><div class="wp-block-group has-base-background-color has-background" style="border-radius:1rem;padding:var(--wp--preset--spacing--40);box-shadow:var(--wp--preset--shadow--sm)"><!-- wp:heading {"level":3,"fontSize":"2xl","textColor":"booming-700"} --><h3 class="wp-block-heading has-booming-700-color has-text-color has-2-xl-font-size">N</h3><!-- /wp:heading --><!-- wp:heading {"level":4,"fontSize":"lg"} --><h4 class="wp-block-heading has-lg-font-size">Narrate</h4><!-- /wp:heading --><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color">Build the narrative that makes your brand sound unmistakably you.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
		<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"border":{"radius":"1rem"},"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40"}},"shadow":"var:preset|shadow|sm"},"backgroundColor":"base"} --><div class="wp-block-group has-base-background-color has-background" style="border-radius:1rem;padding:var(--wp--preset--spacing--40);box-shadow:var(--wp--preset--shadow--sm)"><!-- wp:heading {"level":3,"fontSize":"2xl","textColor":"booming-700"} --><h3 class="wp-block-heading has-booming-700-color has-text-color has-2-xl-font-size">I</h3><!-- /wp:heading --><!-- wp:heading {"level":4,"fontSize":"lg"} --><h4 class="wp-block-heading has-lg-font-size">Implement</h4><!-- /wp:heading --><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color">Ship AI-powered campaigns, funnels, and automations that run.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
		<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"border":{"radius":"1rem"},"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40"}},"shadow":"var:preset|shadow|sm"},"backgroundColor":"base"} --><div class="wp-block-group has-base-background-color has-background" style="border-radius:1rem;padding:var(--wp--preset--spacing--40);box-shadow:var(--wp--preset--shadow--sm)"><!-- wp:heading {"level":3,"fontSize":"2xl","textColor":"booming-700"} --><h3 class="wp-block-heading has-booming-700-color has-text-color has-2-xl-font-size">F</h3><!-- /wp:heading --><!-- wp:heading {"level":4,"fontSize":"lg"} --><h4 class="wp-block-heading has-lg-font-size">Forecast</h4><!-- /wp:heading --><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color">Model ROI and the next 12 months ,  so growth is predictable, not lucky.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
		<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"border":{"radius":"1rem"},"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40"}},"shadow":"var:preset|shadow|sm"},"backgroundColor":"base"} --><div class="wp-block-group has-base-background-color has-background" style="border-radius:1rem;padding:var(--wp--preset--spacing--40);box-shadow:var(--wp--preset--shadow--sm)"><!-- wp:heading {"level":3,"fontSize":"2xl","textColor":"booming-700"} --><h3 class="wp-block-heading has-booming-700-color has-text-color has-2-xl-font-size">Y</h3><!-- /wp:heading --><!-- wp:heading {"level":4,"fontSize":"lg"} --><h4 class="wp-block-heading has-lg-font-size">Yield</h4><!-- /wp:heading --><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color">Optimize, compound, and keep yielding ,  month over month, quarter over quarter.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
	</div>
	<!-- /wp:columns -->
</section>
<!-- /wp:group -->
